FROM node:21-alpine3.18 as build-stage
WORKDIR /app
COPY ./package.json /app
COPY ./src /app/src
COPY ./nest-cli.json /app
COPY ./tsconfig.build.json /app
COPY ./tsconfig.json /app
COPY ./.env /app

RUN npm install

CMD npm run start