version: "3.8"

services:
  backend:
    container_name: base-backend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3003:3003"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - default
